######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 26 10:38:41 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += entry.h newNumber.h phonebook.h
SOURCES += entry.cpp main.cpp newNumber.cpp phonebook.cpp
